# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 960))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 960))
        MainWindow.setBaseSize(QtCore.QSize(1280, 960))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1261, 901))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_dashboard = QtWidgets.QWidget()
        self.tab_dashboard.setObjectName("tab_dashboard")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_dashboard)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 1211, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setGeometry(QtCore.QRect(10, 30, 201, 71))
        self.frame.setStyleSheet("border-width: 1px;\n"
"border-color: gray;\n"
"border-style: solid;\n"
"background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 5, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-style: none")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-style: none")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_dashboard, "")
        self.tab_task_config = QtWidgets.QWidget()
        self.tab_task_config.setObjectName("tab_task_config")
        self.groupBox = QtWidgets.QGroupBox(self.tab_task_config)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 591, 231))
        self.groupBox.setObjectName("groupBox")
        self.progressBar_read_manuals = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_read_manuals.setGeometry(QtCore.QRect(20, 140, 551, 23))
        self.progressBar_read_manuals.setProperty("value", 0)
        self.progressBar_read_manuals.setObjectName("progressBar_read_manuals")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_manuals_directory = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_manuals_directory.setGeometry(QtCore.QRect(90, 30, 371, 31))
        self.lineEdit_manuals_directory.setObjectName("lineEdit_manuals_directory")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(470, 30, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 141, 21))
        self.label_3.setObjectName("label_3")
        self.label_manuals_config_state = QtWidgets.QLabel(self.groupBox)
        self.label_manuals_config_state.setGeometry(QtCore.QRect(170, 110, 181, 21))
        self.label_manuals_config_state.setStyleSheet("color: red")
        self.label_manuals_config_state.setObjectName("label_manuals_config_state")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 30, 61, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.button_verify_manuals_input = QtWidgets.QPushButton(self.groupBox)
        self.button_verify_manuals_input.setGeometry(QtCore.QRect(120, 180, 111, 28))
        self.button_verify_manuals_input.setObjectName("button_verify_manuals_input")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 180, 111, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 180, 111, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 551, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.tab_task_config)
        self.line.setGeometry(QtCore.QRect(620, 20, 20, 821))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_task_parsing = QtWidgets.QGroupBox(self.tab_task_config)
        self.groupBox_task_parsing.setEnabled(False)
        self.groupBox_task_parsing.setGeometry(QtCore.QRect(20, 270, 591, 561))
        self.groupBox_task_parsing.setObjectName("groupBox_task_parsing")
        self.progress_task_parsing = QtWidgets.QProgressBar(self.groupBox_task_parsing)
        self.progress_task_parsing.setGeometry(QtCore.QRect(20, 80, 551, 23))
        self.progress_task_parsing.setProperty("value", 0)
        self.progress_task_parsing.setObjectName("progress_task_parsing")
        self.label_5 = QtWidgets.QLabel(self.groupBox_task_parsing)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self.label_5.setObjectName("label_5")
        self.button_task_confirm = QtWidgets.QPushButton(self.groupBox_task_parsing)
        self.button_task_confirm.setGeometry(QtCore.QRect(180, 510, 111, 31))
        self.button_task_confirm.setObjectName("button_task_confirm")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_task_parsing)
        self.pushButton_8.setGeometry(QtCore.QRect(310, 510, 111, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_task_parsing)
        self.comboBox.setGeometry(QtCore.QRect(160, 30, 331, 31))
        self.comboBox.setObjectName("comboBox")
        self.task_list = QtWidgets.QColumnView(self.groupBox_task_parsing)
        self.task_list.setGeometry(QtCore.QRect(20, 120, 551, 371))
        self.task_list.setObjectName("task_list")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_task_parsing)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 30, 71, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_kin_setup = QtWidgets.QGroupBox(self.tab_task_config)
        self.groupBox_kin_setup.setGeometry(QtCore.QRect(650, 20, 591, 291))
        self.groupBox_kin_setup.setObjectName("groupBox_kin_setup")
        self.button_start_assembly = QtWidgets.QPushButton(self.tab_task_config)
        self.button_start_assembly.setEnabled(False)
        self.button_start_assembly.setGeometry(QtCore.QRect(650, 790, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_start_assembly.setFont(font)
        self.button_start_assembly.setObjectName("button_start_assembly")
        self.button_check_preset_validity = QtWidgets.QPushButton(self.tab_task_config)
        self.button_check_preset_validity.setGeometry(QtCore.QRect(650, 740, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_check_preset_validity.setFont(font)
        self.button_check_preset_validity.setObjectName("button_check_preset_validity")
        self.tabWidget.addTab(self.tab_task_config, "")
        self.tab_logs = QtWidgets.QWidget()
        self.tab_logs.setObjectName("tab_logs")
        self.columnView_2 = QtWidgets.QColumnView(self.tab_logs)
        self.columnView_2.setGeometry(QtCore.QRect(20, 20, 1221, 761))
        self.columnView_2.setObjectName("columnView_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_logs)
        self.pushButton_12.setGeometry(QtCore.QRect(530, 800, 201, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_logs)
        self.pushButton_13.setGeometry(QtCore.QRect(750, 800, 201, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_logs)
        self.pushButton_14.setGeometry(QtCore.QRect(310, 800, 201, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.tabWidget.addTab(self.tab_logs, "")
        self.tab_preference = QtWidgets.QWidget()
        self.tab_preference.setObjectName("tab_preference")
        self.button_increase_number = QtWidgets.QPushButton(self.tab_preference)
        self.button_increase_number.setGeometry(QtCore.QRect(140, 30, 111, 61))
        self.button_increase_number.setObjectName("button_increase_number")
        self.label = QtWidgets.QLabel(self.tab_preference)
        self.label.setGeometry(QtCore.QRect(40, 30, 81, 61))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_preference, "")
        self.tab_manipulation_arm_1 = QtWidgets.QWidget()
        self.tab_manipulation_arm_1.setObjectName("tab_manipulation_arm_1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_manipulation_arm_1)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 80, 591, 691))
        self.groupBox_5.setObjectName("groupBox_5")
        self.fine_x = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.fine_x.setGeometry(QtCore.QRect(120, 50, 71, 31))
        self.fine_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.fine_x.setSuffix("")
        self.fine_x.setDecimals(1)
        self.fine_x.setObjectName("fine_x")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(120, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(200, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(280, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.fine_y = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.fine_y.setGeometry(QtCore.QRect(200, 50, 71, 31))
        self.fine_y.setDecimals(1)
        self.fine_y.setObjectName("fine_y")
        self.fine_z = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.fine_z.setGeometry(QtCore.QRect(280, 50, 71, 31))
        self.fine_z.setDecimals(1)
        self.fine_z.setObjectName("fine_z")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(20, 50, 91, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.label_14.setObjectName("label_14")
        self.normal_y = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.normal_y.setGeometry(QtCore.QRect(200, 90, 71, 31))
        self.normal_y.setDecimals(1)
        self.normal_y.setObjectName("normal_y")
        self.normal_x = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.normal_x.setGeometry(QtCore.QRect(120, 90, 71, 31))
        self.normal_x.setDecimals(1)
        self.normal_x.setObjectName("normal_x")
        self.normal_z = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.normal_z.setGeometry(QtCore.QRect(280, 90, 71, 31))
        self.normal_z.setDecimals(1)
        self.normal_z.setObjectName("normal_z")
        self.large_y = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.large_y.setGeometry(QtCore.QRect(200, 130, 71, 31))
        self.large_y.setDecimals(1)
        self.large_y.setObjectName("large_y")
        self.large_x = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.large_x.setGeometry(QtCore.QRect(120, 130, 71, 31))
        self.large_x.setDecimals(1)
        self.large_x.setObjectName("large_x")
        self.large_z = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.large_z.setGeometry(QtCore.QRect(280, 130, 71, 31))
        self.large_z.setDecimals(1)
        self.large_z.setObjectName("large_z")
        self.linear_jogging = QtWidgets.QFrame(self.groupBox_5)
        self.linear_jogging.setGeometry(QtCore.QRect(20, 200, 551, 451))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.linear_jogging.setFont(font)
        self.linear_jogging.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.linear_jogging.setFrameShadow(QtWidgets.QFrame.Raised)
        self.linear_jogging.setObjectName("linear_jogging")
        self.button_x_plus_large = QtWidgets.QPushButton(self.linear_jogging)
        self.button_x_plus_large.setGeometry(QtCore.QRect(430, 150, 21, 151))
        self.button_x_plus_large.setObjectName("button_x_plus_large")
        self.button_x_minus_fine = QtWidgets.QPushButton(self.linear_jogging)
        self.button_x_minus_fine.setGeometry(QtCore.QRect(80, 150, 61, 151))
        self.button_x_minus_fine.setObjectName("button_x_minus_fine")
        self.button_y_plus_large = QtWidgets.QPushButton(self.linear_jogging)
        self.button_y_plus_large.setGeometry(QtCore.QRect(150, 0, 151, 21))
        self.button_y_plus_large.setObjectName("button_y_plus_large")
        self.button_y_minus_normal = QtWidgets.QPushButton(self.linear_jogging)
        self.button_y_minus_normal.setGeometry(QtCore.QRect(150, 380, 151, 41))
        self.button_y_minus_normal.setObjectName("button_y_minus_normal")
        self.button_z_plus_normal = QtWidgets.QPushButton(self.linear_jogging)
        self.button_z_plus_normal.setGeometry(QtCore.QRect(230, 220, 71, 41))
        self.button_z_plus_normal.setObjectName("button_z_plus_normal")
        self.button_x_plus_normal = QtWidgets.QPushButton(self.linear_jogging)
        self.button_x_plus_normal.setGeometry(QtCore.QRect(380, 150, 41, 151))
        self.button_x_plus_normal.setObjectName("button_x_plus_normal")
        self.button_z_minus_normal = QtWidgets.QPushButton(self.linear_jogging)
        self.button_z_minus_normal.setGeometry(QtCore.QRect(150, 220, 71, 41))
        self.button_z_minus_normal.setObjectName("button_z_minus_normal")
        self.button_z_minus_large = QtWidgets.QPushButton(self.linear_jogging)
        self.button_z_minus_large.setGeometry(QtCore.QRect(150, 270, 71, 31))
        self.button_z_minus_large.setObjectName("button_z_minus_large")
        self.button_y_plus_normal = QtWidgets.QPushButton(self.linear_jogging)
        self.button_y_plus_normal.setGeometry(QtCore.QRect(150, 30, 151, 41))
        self.button_y_plus_normal.setObjectName("button_y_plus_normal")
        self.button_y_minus_fine = QtWidgets.QPushButton(self.linear_jogging)
        self.button_y_minus_fine.setGeometry(QtCore.QRect(150, 310, 151, 61))
        self.button_y_minus_fine.setObjectName("button_y_minus_fine")
        self.button_z_plus_large = QtWidgets.QPushButton(self.linear_jogging)
        self.button_z_plus_large.setGeometry(QtCore.QRect(230, 270, 71, 31))
        self.button_z_plus_large.setObjectName("button_z_plus_large")
        self.button_y_minus_large = QtWidgets.QPushButton(self.linear_jogging)
        self.button_y_minus_large.setGeometry(QtCore.QRect(150, 430, 151, 21))
        self.button_y_minus_large.setObjectName("button_y_minus_large")
        self.button_z_minus_fine = QtWidgets.QPushButton(self.linear_jogging)
        self.button_z_minus_fine.setGeometry(QtCore.QRect(150, 150, 71, 61))
        self.button_z_minus_fine.setObjectName("button_z_minus_fine")
        self.button_x_minus_large = QtWidgets.QPushButton(self.linear_jogging)
        self.button_x_minus_large.setGeometry(QtCore.QRect(0, 150, 21, 151))
        self.button_x_minus_large.setObjectName("button_x_minus_large")
        self.button_y_plus_fine = QtWidgets.QPushButton(self.linear_jogging)
        self.button_y_plus_fine.setGeometry(QtCore.QRect(150, 80, 151, 61))
        self.button_y_plus_fine.setObjectName("button_y_plus_fine")
        self.button_x_plus_fine = QtWidgets.QPushButton(self.linear_jogging)
        self.button_x_plus_fine.setGeometry(QtCore.QRect(310, 150, 61, 151))
        self.button_x_plus_fine.setObjectName("button_x_plus_fine")
        self.button_x_minus_normal = QtWidgets.QPushButton(self.linear_jogging)
        self.button_x_minus_normal.setGeometry(QtCore.QRect(30, 150, 41, 151))
        self.button_x_minus_normal.setObjectName("button_x_minus_normal")
        self.button_z_plus_fine = QtWidgets.QPushButton(self.linear_jogging)
        self.button_z_plus_fine.setGeometry(QtCore.QRect(230, 150, 71, 61))
        self.button_z_plus_fine.setObjectName("button_z_plus_fine")
        self.button_delta_position_5 = QtWidgets.QPushButton(self.linear_jogging)
        self.button_delta_position_5.setGeometry(QtCore.QRect(480, 230, 71, 71))
        self.button_delta_position_5.setObjectName("button_delta_position_5")
        self.button_delta_position_6 = QtWidgets.QPushButton(self.linear_jogging)
        self.button_delta_position_6.setGeometry(QtCore.QRect(480, 150, 71, 71))
        self.button_delta_position_6.setObjectName("button_delta_position_6")
        self.label_gripper_open = QtWidgets.QLabel(self.groupBox_5)
        self.label_gripper_open.setGeometry(QtCore.QRect(370, 50, 201, 21))
        self.label_gripper_open.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_gripper_open.setObjectName("label_gripper_open")
        self.slider_gripper_open = QtWidgets.QSlider(self.groupBox_5)
        self.slider_gripper_open.setGeometry(QtCore.QRect(370, 80, 201, 21))
        self.slider_gripper_open.setMaximum(255)
        self.slider_gripper_open.setSingleStep(5)
        self.slider_gripper_open.setOrientation(QtCore.Qt.Horizontal)
        self.slider_gripper_open.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_gripper_open.setObjectName("slider_gripper_open")
        self.label_gripper_grip = QtWidgets.QLabel(self.groupBox_5)
        self.label_gripper_grip.setGeometry(QtCore.QRect(370, 110, 201, 21))
        self.label_gripper_grip.setObjectName("label_gripper_grip")
        self.slider_gripper_grip = QtWidgets.QSlider(self.groupBox_5)
        self.slider_gripper_grip.setGeometry(QtCore.QRect(370, 140, 201, 21))
        self.slider_gripper_grip.setMaximum(255)
        self.slider_gripper_grip.setSingleStep(5)
        self.slider_gripper_grip.setSliderPosition(255)
        self.slider_gripper_grip.setOrientation(QtCore.Qt.Horizontal)
        self.slider_gripper_grip.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_gripper_grip.setObjectName("slider_gripper_grip")
        self.line_2 = QtWidgets.QFrame(self.tab_manipulation_arm_1)
        self.line_2.setGeometry(QtCore.QRect(620, 80, 20, 701))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.numerical_controls = QtWidgets.QGroupBox(self.tab_manipulation_arm_1)
        self.numerical_controls.setGeometry(QtCore.QRect(650, 80, 591, 311))
        self.numerical_controls.setObjectName("numerical_controls")
        self.label_40 = QtWidgets.QLabel(self.numerical_controls)
        self.label_40.setGeometry(QtCore.QRect(300, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_38 = QtWidgets.QLabel(self.numerical_controls)
        self.label_38.setGeometry(QtCore.QRect(60, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.numerical_controls)
        self.label_39.setGeometry(QtCore.QRect(180, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.lineEdit_pose_x = QtWidgets.QLineEdit(self.numerical_controls)
        self.lineEdit_pose_x.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.lineEdit_pose_x.setObjectName("lineEdit_pose_x")
        self.lineEdit_pose_y = QtWidgets.QLineEdit(self.numerical_controls)
        self.lineEdit_pose_y.setGeometry(QtCore.QRect(140, 60, 101, 31))
        self.lineEdit_pose_y.setObjectName("lineEdit_pose_y")
        self.lineEdit_pose_z = QtWidgets.QLineEdit(self.numerical_controls)
        self.lineEdit_pose_z.setGeometry(QtCore.QRect(260, 60, 101, 31))
        self.lineEdit_pose_z.setObjectName("lineEdit_pose_z")
        self.button_goto_position = QtWidgets.QPushButton(self.numerical_controls)
        self.button_goto_position.setGeometry(QtCore.QRect(490, 30, 81, 91))
        self.button_goto_position.setObjectName("button_goto_position")
        self.button_delta_position = QtWidgets.QPushButton(self.numerical_controls)
        self.button_delta_position.setGeometry(QtCore.QRect(380, 30, 91, 91))
        self.button_delta_position.setObjectName("button_delta_position")
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.numerical_controls)
        self.lineEdit_yaw.setGeometry(QtCore.QRect(260, 170, 101, 31))
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.label_42 = QtWidgets.QLabel(self.numerical_controls)
        self.label_42.setGeometry(QtCore.QRect(50, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_41 = QtWidgets.QLabel(self.numerical_controls)
        self.label_41.setGeometry(QtCore.QRect(290, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.numerical_controls)
        self.lineEdit_pitch.setGeometry(QtCore.QRect(140, 170, 101, 31))
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.lineEdit_roll = QtWidgets.QLineEdit(self.numerical_controls)
        self.lineEdit_roll.setGeometry(QtCore.QRect(20, 170, 101, 31))
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.button_delta_orientation = QtWidgets.QPushButton(self.numerical_controls)
        self.button_delta_orientation.setGeometry(QtCore.QRect(380, 140, 91, 91))
        self.button_delta_orientation.setObjectName("button_delta_orientation")
        self.button_goto_orientation = QtWidgets.QPushButton(self.numerical_controls)
        self.button_goto_orientation.setGeometry(QtCore.QRect(490, 140, 81, 91))
        self.button_goto_orientation.setObjectName("button_goto_orientation")
        self.label_43 = QtWidgets.QLabel(self.numerical_controls)
        self.label_43.setGeometry(QtCore.QRect(160, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.buttron_delta_pose = QtWidgets.QPushButton(self.numerical_controls)
        self.buttron_delta_pose.setGeometry(QtCore.QRect(20, 250, 271, 41))
        self.buttron_delta_pose.setObjectName("buttron_delta_pose")
        self.button_goto_pose = QtWidgets.QPushButton(self.numerical_controls)
        self.button_goto_pose.setGeometry(QtCore.QRect(300, 250, 271, 41))
        self.button_goto_pose.setObjectName("button_goto_pose")
        self.frame_13 = QtWidgets.QFrame(self.numerical_controls)
        self.frame_13.setGeometry(QtCore.QRect(100, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_13.setFont(font)
        self.frame_13.setStyleSheet("border-style: none")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_13)
        self.radioButton_10.setGeometry(QtCore.QRect(0, 0, 108, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_10.setFont(font)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_13)
        self.radioButton_11.setGeometry(QtCore.QRect(110, 0, 71, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_11.setFont(font)
        self.radioButton_11.setObjectName("radioButton_11")
        self.frame_14 = QtWidgets.QFrame(self.numerical_controls)
        self.frame_14.setGeometry(QtCore.QRect(100, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_14.setFont(font)
        self.frame_14.setStyleSheet("border-style: none;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_12.setGeometry(QtCore.QRect(0, 0, 108, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_12.setFont(font)
        self.radioButton_12.setStyleSheet("border-style: none;")
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_13.setGeometry(QtCore.QRect(110, 0, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_13.setFont(font)
        self.radioButton_13.setObjectName("radioButton_13")
        self.end_effector_pose = QtWidgets.QGroupBox(self.tab_manipulation_arm_1)
        self.end_effector_pose.setGeometry(QtCore.QRect(20, 790, 1221, 71))
        self.end_effector_pose.setObjectName("end_effector_pose")
        self.label_52 = QtWidgets.QLabel(self.end_effector_pose)
        self.label_52.setGeometry(QtCore.QRect(610, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.end_effector_pose)
        self.label_53.setGeometry(QtCore.QRect(420, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.end_effector_pose)
        self.label_54.setGeometry(QtCore.QRect(1010, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.end_effector_pose)
        self.label_55.setGeometry(QtCore.QRect(20, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.end_effector_pose)
        self.label_56.setGeometry(QtCore.QRect(220, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.end_effector_pose)
        self.label_57.setGeometry(QtCore.QRect(800, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.x = QtWidgets.QLabel(self.end_effector_pose)
        self.x.setGeometry(QtCore.QRect(50, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x.setFont(font)
        self.x.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.x.setObjectName("x")
        self.y = QtWidgets.QLabel(self.end_effector_pose)
        self.y.setGeometry(QtCore.QRect(250, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y.setFont(font)
        self.y.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.y.setObjectName("y")
        self.z = QtWidgets.QLabel(self.end_effector_pose)
        self.z.setGeometry(QtCore.QRect(450, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.z.setFont(font)
        self.z.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.z.setObjectName("z")
        self.r = QtWidgets.QLabel(self.end_effector_pose)
        self.r.setGeometry(QtCore.QRect(660, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r.setFont(font)
        self.r.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.r.setObjectName("r")
        self.p = QtWidgets.QLabel(self.end_effector_pose)
        self.p.setGeometry(QtCore.QRect(860, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p.setFont(font)
        self.p.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.p.setObjectName("p")
        self.y_ = QtWidgets.QLabel(self.end_effector_pose)
        self.y_.setGeometry(QtCore.QRect(1060, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y_.setFont(font)
        self.y_.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.y_.setObjectName("y_")
        self.joint_revolution = QtWidgets.QGroupBox(self.tab_manipulation_arm_1)
        self.joint_revolution.setGeometry(QtCore.QRect(650, 410, 591, 361))
        self.joint_revolution.setObjectName("joint_revolution")
        self.slider_joint1_angle = QtWidgets.QSlider(self.joint_revolution)
        self.slider_joint1_angle.setGeometry(QtCore.QRect(80, 80, 391, 22))
        self.slider_joint1_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint1_angle.setObjectName("slider_joint1_angle")
        self.label_44 = QtWidgets.QLabel(self.joint_revolution)
        self.label_44.setGeometry(QtCore.QRect(20, 80, 51, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.joint_revolution)
        self.label_45.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.label_45.setObjectName("label_45")
        self.label_47 = QtWidgets.QLabel(self.joint_revolution)
        self.label_47.setGeometry(QtCore.QRect(20, 115, 51, 21))
        self.label_47.setObjectName("label_47")
        self.slider_joint2_angle = QtWidgets.QSlider(self.joint_revolution)
        self.slider_joint2_angle.setGeometry(QtCore.QRect(80, 115, 391, 22))
        self.slider_joint2_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint2_angle.setObjectName("slider_joint2_angle")
        self.label_48 = QtWidgets.QLabel(self.joint_revolution)
        self.label_48.setGeometry(QtCore.QRect(20, 150, 51, 21))
        self.label_48.setObjectName("label_48")
        self.slider_joint3_angle = QtWidgets.QSlider(self.joint_revolution)
        self.slider_joint3_angle.setGeometry(QtCore.QRect(80, 150, 391, 22))
        self.slider_joint3_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint3_angle.setObjectName("slider_joint3_angle")
        self.label_49 = QtWidgets.QLabel(self.joint_revolution)
        self.label_49.setGeometry(QtCore.QRect(20, 185, 51, 21))
        self.label_49.setObjectName("label_49")
        self.slider_joint4_angle = QtWidgets.QSlider(self.joint_revolution)
        self.slider_joint4_angle.setGeometry(QtCore.QRect(80, 185, 391, 22))
        self.slider_joint4_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint4_angle.setObjectName("slider_joint4_angle")
        self.label_50 = QtWidgets.QLabel(self.joint_revolution)
        self.label_50.setGeometry(QtCore.QRect(20, 220, 51, 21))
        self.label_50.setObjectName("label_50")
        self.slider_joint5_angle = QtWidgets.QSlider(self.joint_revolution)
        self.slider_joint5_angle.setGeometry(QtCore.QRect(80, 220, 391, 22))
        self.slider_joint5_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint5_angle.setObjectName("slider_joint5_angle")
        self.label_51 = QtWidgets.QLabel(self.joint_revolution)
        self.label_51.setGeometry(QtCore.QRect(20, 255, 51, 21))
        self.label_51.setObjectName("label_51")
        self.slider_joint6_angle = QtWidgets.QSlider(self.joint_revolution)
        self.slider_joint6_angle.setGeometry(QtCore.QRect(80, 255, 391, 22))
        self.slider_joint6_angle.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint6_angle.setObjectName("slider_joint6_angle")
        self.pushButton_88 = QtWidgets.QPushButton(self.joint_revolution)
        self.pushButton_88.setGeometry(QtCore.QRect(20, 300, 271, 41))
        self.pushButton_88.setObjectName("pushButton_88")
        self.pushButton_87 = QtWidgets.QPushButton(self.joint_revolution)
        self.pushButton_87.setGeometry(QtCore.QRect(300, 300, 271, 41))
        self.pushButton_87.setObjectName("pushButton_87")
        self.button_reset_angle = QtWidgets.QPushButton(self.joint_revolution)
        self.button_reset_angle.setGeometry(QtCore.QRect(350, 30, 221, 31))
        self.button_reset_angle.setObjectName("button_reset_angle")
        self.spinbox_joint1_angle = QtWidgets.QDoubleSpinBox(self.joint_revolution)
        self.spinbox_joint1_angle.setGeometry(QtCore.QRect(480, 75, 91, 31))
        self.spinbox_joint1_angle.setObjectName("spinbox_joint1_angle")
        self.spinbox_joint2_angle = QtWidgets.QDoubleSpinBox(self.joint_revolution)
        self.spinbox_joint2_angle.setGeometry(QtCore.QRect(480, 110, 91, 31))
        self.spinbox_joint2_angle.setObjectName("spinbox_joint2_angle")
        self.spinbox_joint3_angle = QtWidgets.QDoubleSpinBox(self.joint_revolution)
        self.spinbox_joint3_angle.setGeometry(QtCore.QRect(480, 145, 91, 31))
        self.spinbox_joint3_angle.setObjectName("spinbox_joint3_angle")
        self.spinbox_joint4_angle = QtWidgets.QDoubleSpinBox(self.joint_revolution)
        self.spinbox_joint4_angle.setGeometry(QtCore.QRect(480, 180, 91, 31))
        self.spinbox_joint4_angle.setObjectName("spinbox_joint4_angle")
        self.spinbox_joint5_angle = QtWidgets.QDoubleSpinBox(self.joint_revolution)
        self.spinbox_joint5_angle.setGeometry(QtCore.QRect(480, 215, 91, 31))
        self.spinbox_joint5_angle.setObjectName("spinbox_joint5_angle")
        self.spinbox_joint6_angle = QtWidgets.QDoubleSpinBox(self.joint_revolution)
        self.spinbox_joint6_angle.setGeometry(QtCore.QRect(480, 250, 91, 31))
        self.spinbox_joint6_angle.setObjectName("spinbox_joint6_angle")
        self.frame_15 = QtWidgets.QFrame(self.joint_revolution)
        self.frame_15.setGeometry(QtCore.QRect(120, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_15.setFont(font)
        self.frame_15.setStyleSheet("border-style: none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.radioButton_34 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_34.setGeometry(QtCore.QRect(0, 0, 108, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_34.setFont(font)
        self.radioButton_34.setStyleSheet("border-style: none;")
        self.radioButton_34.setObjectName("radioButton_34")
        self.radioButton_35 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_35.setGeometry(QtCore.QRect(110, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_35.setFont(font)
        self.radioButton_35.setObjectName("radioButton_35")
        self.label_46 = QtWidgets.QLabel(self.tab_manipulation_arm_1)
        self.label_46.setGeometry(QtCore.QRect(20, 20, 1221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("border: 2px solid black;\n"
"background-color: white;")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.tabWidget.addTab(self.tab_manipulation_arm_1, "")
        self.tab_manipulation_arm_2 = QtWidgets.QWidget()
        self.tab_manipulation_arm_2.setObjectName("tab_manipulation_arm_2")
        self.numerical_controls_2 = QtWidgets.QGroupBox(self.tab_manipulation_arm_2)
        self.numerical_controls_2.setGeometry(QtCore.QRect(650, 80, 591, 311))
        self.numerical_controls_2.setObjectName("numerical_controls_2")
        self.label_70 = QtWidgets.QLabel(self.numerical_controls_2)
        self.label_70.setGeometry(QtCore.QRect(300, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.label_85 = QtWidgets.QLabel(self.numerical_controls_2)
        self.label_85.setGeometry(QtCore.QRect(60, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_85.setFont(font)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.numerical_controls_2)
        self.label_86.setGeometry(QtCore.QRect(180, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_86.setFont(font)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.lineEdit_pose_x_2 = QtWidgets.QLineEdit(self.numerical_controls_2)
        self.lineEdit_pose_x_2.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.lineEdit_pose_x_2.setObjectName("lineEdit_pose_x_2")
        self.lineEdit_pose_y_2 = QtWidgets.QLineEdit(self.numerical_controls_2)
        self.lineEdit_pose_y_2.setGeometry(QtCore.QRect(140, 60, 101, 31))
        self.lineEdit_pose_y_2.setObjectName("lineEdit_pose_y_2")
        self.lineEdit_pose_z_2 = QtWidgets.QLineEdit(self.numerical_controls_2)
        self.lineEdit_pose_z_2.setGeometry(QtCore.QRect(260, 60, 101, 31))
        self.lineEdit_pose_z_2.setObjectName("lineEdit_pose_z_2")
        self.button_goto_position_2 = QtWidgets.QPushButton(self.numerical_controls_2)
        self.button_goto_position_2.setGeometry(QtCore.QRect(490, 30, 81, 91))
        self.button_goto_position_2.setObjectName("button_goto_position_2")
        self.button_delta_position_2 = QtWidgets.QPushButton(self.numerical_controls_2)
        self.button_delta_position_2.setGeometry(QtCore.QRect(380, 30, 91, 91))
        self.button_delta_position_2.setObjectName("button_delta_position_2")
        self.lineEdit_yaw_2 = QtWidgets.QLineEdit(self.numerical_controls_2)
        self.lineEdit_yaw_2.setGeometry(QtCore.QRect(260, 170, 101, 31))
        self.lineEdit_yaw_2.setObjectName("lineEdit_yaw_2")
        self.label_87 = QtWidgets.QLabel(self.numerical_controls_2)
        self.label_87.setGeometry(QtCore.QRect(50, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_87.setFont(font)
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.numerical_controls_2)
        self.label_88.setGeometry(QtCore.QRect(290, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_88.setFont(font)
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.lineEdit_pitch_2 = QtWidgets.QLineEdit(self.numerical_controls_2)
        self.lineEdit_pitch_2.setGeometry(QtCore.QRect(140, 170, 101, 31))
        self.lineEdit_pitch_2.setObjectName("lineEdit_pitch_2")
        self.lineEdit_roll_2 = QtWidgets.QLineEdit(self.numerical_controls_2)
        self.lineEdit_roll_2.setGeometry(QtCore.QRect(20, 170, 101, 31))
        self.lineEdit_roll_2.setObjectName("lineEdit_roll_2")
        self.button_delta_orientation_2 = QtWidgets.QPushButton(self.numerical_controls_2)
        self.button_delta_orientation_2.setGeometry(QtCore.QRect(380, 140, 91, 91))
        self.button_delta_orientation_2.setObjectName("button_delta_orientation_2")
        self.button_goto_orientation_2 = QtWidgets.QPushButton(self.numerical_controls_2)
        self.button_goto_orientation_2.setGeometry(QtCore.QRect(490, 140, 81, 91))
        self.button_goto_orientation_2.setObjectName("button_goto_orientation_2")
        self.label_89 = QtWidgets.QLabel(self.numerical_controls_2)
        self.label_89.setGeometry(QtCore.QRect(160, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_89.setFont(font)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.buttron_delta_pose_2 = QtWidgets.QPushButton(self.numerical_controls_2)
        self.buttron_delta_pose_2.setGeometry(QtCore.QRect(20, 250, 271, 41))
        self.buttron_delta_pose_2.setObjectName("buttron_delta_pose_2")
        self.button_goto_pose_2 = QtWidgets.QPushButton(self.numerical_controls_2)
        self.button_goto_pose_2.setGeometry(QtCore.QRect(300, 250, 271, 41))
        self.button_goto_pose_2.setObjectName("button_goto_pose_2")
        self.frame_16 = QtWidgets.QFrame(self.numerical_controls_2)
        self.frame_16.setGeometry(QtCore.QRect(100, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_16.setFont(font)
        self.frame_16.setStyleSheet("border-style: none")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_14.setGeometry(QtCore.QRect(0, 0, 108, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_14.setFont(font)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_15.setGeometry(QtCore.QRect(110, 0, 71, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_15.setFont(font)
        self.radioButton_15.setObjectName("radioButton_15")
        self.frame_17 = QtWidgets.QFrame(self.numerical_controls_2)
        self.frame_17.setGeometry(QtCore.QRect(100, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_17.setFont(font)
        self.frame_17.setStyleSheet("border-style: none;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.radioButton_25 = QtWidgets.QRadioButton(self.frame_17)
        self.radioButton_25.setGeometry(QtCore.QRect(0, 0, 108, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_25.setFont(font)
        self.radioButton_25.setStyleSheet("border-style: none;")
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(self.frame_17)
        self.radioButton_26.setGeometry(QtCore.QRect(110, 0, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_26.setFont(font)
        self.radioButton_26.setObjectName("radioButton_26")
        self.end_effector_pose_2 = QtWidgets.QGroupBox(self.tab_manipulation_arm_2)
        self.end_effector_pose_2.setGeometry(QtCore.QRect(20, 790, 1221, 71))
        self.end_effector_pose_2.setObjectName("end_effector_pose_2")
        self.label_90 = QtWidgets.QLabel(self.end_effector_pose_2)
        self.label_90.setGeometry(QtCore.QRect(610, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_90.setFont(font)
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.end_effector_pose_2)
        self.label_91.setGeometry(QtCore.QRect(420, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.end_effector_pose_2)
        self.label_92.setGeometry(QtCore.QRect(1010, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_92.setFont(font)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.end_effector_pose_2)
        self.label_93.setGeometry(QtCore.QRect(20, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_93.setFont(font)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.end_effector_pose_2)
        self.label_94.setGeometry(QtCore.QRect(220, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_94.setFont(font)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.end_effector_pose_2)
        self.label_95.setGeometry(QtCore.QRect(800, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_95.setFont(font)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.tab_manipulation_arm_2)
        self.label_96.setGeometry(QtCore.QRect(20, 20, 1221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_96.setFont(font)
        self.label_96.setStyleSheet("border: 2px solid black;\n"
"background-color: white;")
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_manipulation_arm_2)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 80, 591, 691))
        self.groupBox_6.setObjectName("groupBox_6")
        self.fine_x_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.fine_x_2.setGeometry(QtCore.QRect(120, 60, 81, 31))
        self.fine_x_2.setObjectName("fine_x_2")
        self.label_97 = QtWidgets.QLabel(self.groupBox_6)
        self.label_97.setGeometry(QtCore.QRect(150, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_97.setFont(font)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.groupBox_6)
        self.label_98.setGeometry(QtCore.QRect(240, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.groupBox_6)
        self.label_99.setGeometry(QtCore.QRect(330, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_99.setFont(font)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.fine_y_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.fine_y_2.setGeometry(QtCore.QRect(210, 60, 81, 31))
        self.fine_y_2.setObjectName("fine_y_2")
        self.fine_z_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.fine_z_2.setGeometry(QtCore.QRect(300, 60, 81, 31))
        self.fine_z_2.setObjectName("fine_z_2")
        self.label_100 = QtWidgets.QLabel(self.groupBox_6)
        self.label_100.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.groupBox_6)
        self.label_101.setGeometry(QtCore.QRect(20, 100, 91, 31))
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(self.groupBox_6)
        self.label_102.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.label_102.setObjectName("label_102")
        self.normal_y_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.normal_y_2.setGeometry(QtCore.QRect(210, 100, 81, 31))
        self.normal_y_2.setObjectName("normal_y_2")
        self.normal_x_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.normal_x_2.setGeometry(QtCore.QRect(120, 100, 81, 31))
        self.normal_x_2.setObjectName("normal_x_2")
        self.normal_z_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.normal_z_2.setGeometry(QtCore.QRect(300, 100, 81, 31))
        self.normal_z_2.setObjectName("normal_z_2")
        self.large_y_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.large_y_2.setGeometry(QtCore.QRect(210, 140, 81, 31))
        self.large_y_2.setObjectName("large_y_2")
        self.large_x_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.large_x_2.setGeometry(QtCore.QRect(120, 140, 81, 31))
        self.large_x_2.setObjectName("large_x_2")
        self.large_z_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.large_z_2.setGeometry(QtCore.QRect(300, 140, 81, 31))
        self.large_z_2.setObjectName("large_z_2")
        self.label_103 = QtWidgets.QLabel(self.groupBox_6)
        self.label_103.setGeometry(QtCore.QRect(460, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_103.setFont(font)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_3.setGeometry(QtCore.QRect(400, 60, 171, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.radioButton_27 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_27.setGeometry(QtCore.QRect(30, 15, 108, 19))
        self.radioButton_27.setAutoFillBackground(False)
        self.radioButton_27.setObjectName("radioButton_27")
        self.radioButton_28 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_28.setGeometry(QtCore.QRect(30, 45, 108, 19))
        self.radioButton_28.setObjectName("radioButton_28")
        self.radioButton_29 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_29.setGeometry(QtCore.QRect(30, 75, 108, 19))
        self.radioButton_29.setObjectName("radioButton_29")
        self.linear_jogging_2 = QtWidgets.QFrame(self.groupBox_6)
        self.linear_jogging_2.setGeometry(QtCore.QRect(50, 190, 481, 481))
        self.linear_jogging_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.linear_jogging_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.linear_jogging_2.setObjectName("linear_jogging_2")
        self.button_x_plus_large_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_x_plus_large_2.setGeometry(QtCore.QRect(450, 160, 21, 161))
        self.button_x_plus_large_2.setObjectName("button_x_plus_large_2")
        self.button_x_minus_fine_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_x_minus_fine_2.setGeometry(QtCore.QRect(90, 160, 61, 161))
        self.button_x_minus_fine_2.setObjectName("button_x_minus_fine_2")
        self.button_y_plus_large_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_y_plus_large_2.setGeometry(QtCore.QRect(160, 10, 161, 21))
        self.button_y_plus_large_2.setObjectName("button_y_plus_large_2")
        self.button_y_minus_normal_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_y_minus_normal_2.setGeometry(QtCore.QRect(160, 400, 161, 41))
        self.button_y_minus_normal_2.setObjectName("button_y_minus_normal_2")
        self.button_z_plus_normal_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_z_plus_normal_2.setGeometry(QtCore.QRect(250, 230, 71, 51))
        self.button_z_plus_normal_2.setObjectName("button_z_plus_normal_2")
        self.button_x_plus_normal_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_x_plus_normal_2.setGeometry(QtCore.QRect(400, 160, 41, 161))
        self.button_x_plus_normal_2.setObjectName("button_x_plus_normal_2")
        self.button_z_minus_normal_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_z_minus_normal_2.setGeometry(QtCore.QRect(160, 230, 71, 51))
        self.button_z_minus_normal_2.setObjectName("button_z_minus_normal_2")
        self.button_z_minus_large_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_z_minus_large_2.setGeometry(QtCore.QRect(160, 290, 71, 31))
        self.button_z_minus_large_2.setObjectName("button_z_minus_large_2")
        self.button_y_plus_normal_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_y_plus_normal_2.setGeometry(QtCore.QRect(160, 40, 161, 41))
        self.button_y_plus_normal_2.setObjectName("button_y_plus_normal_2")
        self.button_y_minus_fine_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_y_minus_fine_2.setGeometry(QtCore.QRect(160, 330, 161, 61))
        self.button_y_minus_fine_2.setObjectName("button_y_minus_fine_2")
        self.button_z_plus_large_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_z_plus_large_2.setGeometry(QtCore.QRect(250, 290, 71, 31))
        self.button_z_plus_large_2.setObjectName("button_z_plus_large_2")
        self.button_y_minus_large_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_y_minus_large_2.setGeometry(QtCore.QRect(160, 450, 161, 21))
        self.button_y_minus_large_2.setObjectName("button_y_minus_large_2")
        self.button_z_minus_fine_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_z_minus_fine_2.setGeometry(QtCore.QRect(160, 160, 71, 61))
        self.button_z_minus_fine_2.setObjectName("button_z_minus_fine_2")
        self.button_x_minus_large_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_x_minus_large_2.setGeometry(QtCore.QRect(10, 160, 21, 161))
        self.button_x_minus_large_2.setObjectName("button_x_minus_large_2")
        self.button_y_plus_fine_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_y_plus_fine_2.setGeometry(QtCore.QRect(160, 90, 161, 61))
        self.button_y_plus_fine_2.setObjectName("button_y_plus_fine_2")
        self.button_x_plus_fine_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_x_plus_fine_2.setGeometry(QtCore.QRect(330, 160, 61, 161))
        self.button_x_plus_fine_2.setObjectName("button_x_plus_fine_2")
        self.button_x_minus_normal_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_x_minus_normal_2.setGeometry(QtCore.QRect(40, 160, 41, 161))
        self.button_x_minus_normal_2.setObjectName("button_x_minus_normal_2")
        self.button_z_plus_fine_2 = QtWidgets.QPushButton(self.linear_jogging_2)
        self.button_z_plus_fine_2.setGeometry(QtCore.QRect(250, 160, 71, 61))
        self.button_z_plus_fine_2.setObjectName("button_z_plus_fine_2")
        self.line_5 = QtWidgets.QFrame(self.tab_manipulation_arm_2)
        self.line_5.setGeometry(QtCore.QRect(620, 80, 20, 701))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.joint_revolution_2 = QtWidgets.QGroupBox(self.tab_manipulation_arm_2)
        self.joint_revolution_2.setGeometry(QtCore.QRect(650, 410, 591, 361))
        self.joint_revolution_2.setObjectName("joint_revolution_2")
        self.slider_joint1_angle_2 = QtWidgets.QSlider(self.joint_revolution_2)
        self.slider_joint1_angle_2.setGeometry(QtCore.QRect(80, 80, 391, 22))
        self.slider_joint1_angle_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint1_angle_2.setObjectName("slider_joint1_angle_2")
        self.label_104 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_104.setGeometry(QtCore.QRect(20, 80, 51, 21))
        self.label_104.setObjectName("label_104")
        self.label_105 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_105.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.label_105.setObjectName("label_105")
        self.label_106 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_106.setGeometry(QtCore.QRect(20, 115, 51, 21))
        self.label_106.setObjectName("label_106")
        self.slider_joint2_angle_2 = QtWidgets.QSlider(self.joint_revolution_2)
        self.slider_joint2_angle_2.setGeometry(QtCore.QRect(80, 115, 391, 22))
        self.slider_joint2_angle_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint2_angle_2.setObjectName("slider_joint2_angle_2")
        self.label_107 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_107.setGeometry(QtCore.QRect(20, 150, 51, 21))
        self.label_107.setObjectName("label_107")
        self.slider_joint3_angle_2 = QtWidgets.QSlider(self.joint_revolution_2)
        self.slider_joint3_angle_2.setGeometry(QtCore.QRect(80, 150, 391, 22))
        self.slider_joint3_angle_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint3_angle_2.setObjectName("slider_joint3_angle_2")
        self.label_108 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_108.setGeometry(QtCore.QRect(20, 185, 51, 21))
        self.label_108.setObjectName("label_108")
        self.slider_joint4_angle_2 = QtWidgets.QSlider(self.joint_revolution_2)
        self.slider_joint4_angle_2.setGeometry(QtCore.QRect(80, 185, 391, 22))
        self.slider_joint4_angle_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint4_angle_2.setObjectName("slider_joint4_angle_2")
        self.label_109 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_109.setGeometry(QtCore.QRect(20, 220, 51, 21))
        self.label_109.setObjectName("label_109")
        self.slider_joint5_angle_2 = QtWidgets.QSlider(self.joint_revolution_2)
        self.slider_joint5_angle_2.setGeometry(QtCore.QRect(80, 220, 391, 22))
        self.slider_joint5_angle_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint5_angle_2.setObjectName("slider_joint5_angle_2")
        self.label_110 = QtWidgets.QLabel(self.joint_revolution_2)
        self.label_110.setGeometry(QtCore.QRect(20, 255, 51, 21))
        self.label_110.setObjectName("label_110")
        self.slider_joint6_angle_2 = QtWidgets.QSlider(self.joint_revolution_2)
        self.slider_joint6_angle_2.setGeometry(QtCore.QRect(80, 255, 391, 22))
        self.slider_joint6_angle_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint6_angle_2.setObjectName("slider_joint6_angle_2")
        self.pushButton_89 = QtWidgets.QPushButton(self.joint_revolution_2)
        self.pushButton_89.setGeometry(QtCore.QRect(20, 300, 271, 41))
        self.pushButton_89.setObjectName("pushButton_89")
        self.pushButton_117 = QtWidgets.QPushButton(self.joint_revolution_2)
        self.pushButton_117.setGeometry(QtCore.QRect(300, 300, 271, 41))
        self.pushButton_117.setObjectName("pushButton_117")
        self.button_reset_angle_2 = QtWidgets.QPushButton(self.joint_revolution_2)
        self.button_reset_angle_2.setGeometry(QtCore.QRect(350, 30, 221, 31))
        self.button_reset_angle_2.setObjectName("button_reset_angle_2")
        self.spinbox_joint1_angle_2 = QtWidgets.QDoubleSpinBox(self.joint_revolution_2)
        self.spinbox_joint1_angle_2.setGeometry(QtCore.QRect(480, 75, 91, 31))
        self.spinbox_joint1_angle_2.setObjectName("spinbox_joint1_angle_2")
        self.spinbox_joint2_angle_2 = QtWidgets.QDoubleSpinBox(self.joint_revolution_2)
        self.spinbox_joint2_angle_2.setGeometry(QtCore.QRect(480, 110, 91, 31))
        self.spinbox_joint2_angle_2.setObjectName("spinbox_joint2_angle_2")
        self.spinbox_joint3_angle_2 = QtWidgets.QDoubleSpinBox(self.joint_revolution_2)
        self.spinbox_joint3_angle_2.setGeometry(QtCore.QRect(480, 145, 91, 31))
        self.spinbox_joint3_angle_2.setObjectName("spinbox_joint3_angle_2")
        self.spinbox_joint4_angle_2 = QtWidgets.QDoubleSpinBox(self.joint_revolution_2)
        self.spinbox_joint4_angle_2.setGeometry(QtCore.QRect(480, 180, 91, 31))
        self.spinbox_joint4_angle_2.setObjectName("spinbox_joint4_angle_2")
        self.spinbox_joint5_angle_2 = QtWidgets.QDoubleSpinBox(self.joint_revolution_2)
        self.spinbox_joint5_angle_2.setGeometry(QtCore.QRect(480, 215, 91, 31))
        self.spinbox_joint5_angle_2.setObjectName("spinbox_joint5_angle_2")
        self.spinbox_joint6_angle_2 = QtWidgets.QDoubleSpinBox(self.joint_revolution_2)
        self.spinbox_joint6_angle_2.setGeometry(QtCore.QRect(480, 250, 91, 31))
        self.spinbox_joint6_angle_2.setObjectName("spinbox_joint6_angle_2")
        self.frame_18 = QtWidgets.QFrame(self.joint_revolution_2)
        self.frame_18.setGeometry(QtCore.QRect(120, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_18.setFont(font)
        self.frame_18.setStyleSheet("border-style: none;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.radioButton_36 = QtWidgets.QRadioButton(self.frame_18)
        self.radioButton_36.setGeometry(QtCore.QRect(0, 0, 108, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_36.setFont(font)
        self.radioButton_36.setStyleSheet("border-style: none;")
        self.radioButton_36.setObjectName("radioButton_36")
        self.radioButton_37 = QtWidgets.QRadioButton(self.frame_18)
        self.radioButton_37.setGeometry(QtCore.QRect(110, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.radioButton_37.setFont(font)
        self.radioButton_37.setObjectName("radioButton_37")
        self.tabWidget.addTab(self.tab_manipulation_arm_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(20, 20, 531, 791))
        self.listView.setObjectName("listView")
        self.define_task = QtWidgets.QGroupBox(self.tab)
        self.define_task.setGeometry(QtCore.QRect(570, 10, 671, 196))
        self.define_task.setObjectName("define_task")
        self.task_type = QtWidgets.QGroupBox(self.define_task)
        self.task_type.setGeometry(QtCore.QRect(20, 25, 161, 151))
        self.task_type.setObjectName("task_type")
        self.radioButton = QtWidgets.QRadioButton(self.task_type)
        self.radioButton.setGeometry(QtCore.QRect(10, 25, 141, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.task_type)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 100, 141, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.task_type)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 125, 141, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_30 = QtWidgets.QRadioButton(self.task_type)
        self.radioButton_30.setGeometry(QtCore.QRect(10, 75, 141, 19))
        self.radioButton_30.setObjectName("radioButton_30")
        self.radioButton_31 = QtWidgets.QRadioButton(self.task_type)
        self.radioButton_31.setGeometry(QtCore.QRect(10, 50, 141, 19))
        self.radioButton_31.setObjectName("radioButton_31")
        self.label_gripper_grip_2 = QtWidgets.QLabel(self.define_task)
        self.label_gripper_grip_2.setGeometry(QtCore.QRect(190, 70, 101, 31))
        self.label_gripper_grip_2.setObjectName("label_gripper_grip_2")
        self.label_gripper_open_2 = QtWidgets.QLabel(self.define_task)
        self.label_gripper_open_2.setGeometry(QtCore.QRect(190, 30, 101, 31))
        self.label_gripper_open_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_gripper_open_2.setObjectName("label_gripper_open_2")
        self.spinBox = QtWidgets.QSpinBox(self.define_task)
        self.spinBox.setGeometry(QtCore.QRect(290, 30, 61, 31))
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.define_task)
        self.spinBox_2.setGeometry(QtCore.QRect(290, 70, 61, 31))
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 820, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 820, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(460, 820, 91, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(120, 820, 91, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(220, 820, 131, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuPreferences = QtWidgets.QMenu(self.menuBar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionRobot_Preference = QtWidgets.QAction(MainWindow)
        self.actionRobot_Preference.setObjectName("actionRobot_Preference")
        self.actionController_Preference = QtWidgets.QAction(MainWindow)
        self.actionController_Preference.setObjectName("actionController_Preference")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen_Configuration = QtWidgets.QAction(MainWindow)
        self.actionOpen_Configuration.setObjectName("actionOpen_Configuration")
        self.actionSave_Configuration_as_File = QtWidgets.QAction(MainWindow)
        self.actionSave_Configuration_as_File.setObjectName("actionSave_Configuration_as_File")
        self.menuFile.addAction(self.actionOpen_Configuration)
        self.menuFile.addAction(self.actionSave_Configuration_as_File)
        self.menuPreferences.addAction(self.actionRobot_Preference)
        self.menuPreferences.addAction(self.actionController_Preference)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuPreferences.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RISE Furniture Assembler Control Panel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Current Status"))
        self.label_8.setText(_translate("MainWindow", "Idle/Busy"))
        self.label_9.setText(_translate("MainWindow", "Idle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dashboard), _translate("MainWindow", "Dashboard"))
        self.groupBox.setTitle(_translate("MainWindow", "Assembly Manuals"))
        self.label_2.setText(_translate("MainWindow", "Directory:"))
        self.pushButton.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Configuration Status:"))
        self.label_manuals_config_state.setText(_translate("MainWindow", "Configuration Incomplete!"))
        self.pushButton_2.setText(_translate("MainWindow", "Load"))
        self.button_verify_manuals_input.setText(_translate("MainWindow", "Verify Input"))
        self.pushButton_4.setText(_translate("MainWindow", "Reset"))
        self.pushButton_9.setText(_translate("MainWindow", "Confirm"))
        self.label_10.setText(_translate("MainWindow", "Directory is not selected or files are not loaded!"))
        self.groupBox_task_parsing.setTitle(_translate("MainWindow", "Task Parsing (Assembly manuals should be loaded first)"))
        self.label_5.setText(_translate("MainWindow", "Recognition Model:"))
        self.button_task_confirm.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_8.setText(_translate("MainWindow", "Reset"))
        self.pushButton_5.setText(_translate("MainWindow", "Parse!"))
        self.groupBox_kin_setup.setTitle(_translate("MainWindow", "Kinetics / Kinematics Setup"))
        self.button_start_assembly.setText(_translate("MainWindow", "Start Assembly"))
        self.button_check_preset_validity.setText(_translate("MainWindow", "Check Preset Validity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_task_config), _translate("MainWindow", "Task Configurations"))
        self.pushButton_12.setText(_translate("MainWindow", "Save Log to FIle"))
        self.pushButton_13.setText(_translate("MainWindow", "Pause Logging"))
        self.pushButton_14.setText(_translate("MainWindow", "Delete Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_logs), _translate("MainWindow", "Logs"))
        self.button_increase_number.setText(_translate("MainWindow", "Increase\n"
"Number"))
        self.label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preference), _translate("MainWindow", "Preference"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Linear Jogging"))
        self.label_6.setText(_translate("MainWindow", "X"))
        self.label_7.setText(_translate("MainWindow", "Y"))
        self.label_11.setText(_translate("MainWindow", "Z"))
        self.label_12.setText(_translate("MainWindow", "Fine Step"))
        self.label_13.setText(_translate("MainWindow", "Normal Step"))
        self.label_14.setText(_translate("MainWindow", "Large Step"))
        self.button_x_plus_large.setText(_translate("MainWindow", "+\n"
"+\n"
"+"))
        self.button_x_minus_fine.setText(_translate("MainWindow", "x\n"
"-"))
        self.button_y_plus_large.setText(_translate("MainWindow", "+++"))
        self.button_y_minus_normal.setText(_translate("MainWindow", "y\n"
"--"))
        self.button_z_plus_normal.setText(_translate("MainWindow", "z\n"
"++"))
        self.button_x_plus_normal.setText(_translate("MainWindow", "x\n"
"++"))
        self.button_z_minus_normal.setText(_translate("MainWindow", "z\n"
"--"))
        self.button_z_minus_large.setText(_translate("MainWindow", "---"))
        self.button_y_plus_normal.setText(_translate("MainWindow", "y\n"
"++"))
        self.button_y_minus_fine.setText(_translate("MainWindow", "y\n"
"-"))
        self.button_z_plus_large.setText(_translate("MainWindow", "+++"))
        self.button_y_minus_large.setText(_translate("MainWindow", "---"))
        self.button_z_minus_fine.setText(_translate("MainWindow", "z\n"
"-"))
        self.button_x_minus_large.setText(_translate("MainWindow", "-\n"
"-\n"
"-"))
        self.button_y_plus_fine.setText(_translate("MainWindow", "y\n"
"+"))
        self.button_x_plus_fine.setText(_translate("MainWindow", "x\n"
"+"))
        self.button_x_minus_normal.setText(_translate("MainWindow", "x\n"
"--"))
        self.button_z_plus_fine.setText(_translate("MainWindow", "z\n"
"+"))
        self.button_delta_position_5.setText(_translate("MainWindow", "Close\n"
"Gripper"))
        self.button_delta_position_6.setText(_translate("MainWindow", "Open\n"
"Gripper"))
        self.label_gripper_open.setText(_translate("MainWindow", "Gripper Open: 0"))
        self.label_gripper_grip.setText(_translate("MainWindow", "Gripper Grip: 255"))
        self.numerical_controls.setTitle(_translate("MainWindow", "Numerical Control - Pose"))
        self.label_40.setText(_translate("MainWindow", "Z"))
        self.label_38.setText(_translate("MainWindow", "X"))
        self.label_39.setText(_translate("MainWindow", "Y"))
        self.button_goto_position.setText(_translate("MainWindow", "GOTO\n"
"Position"))
        self.button_delta_position.setText(_translate("MainWindow", "DELTA\n"
"Position"))
        self.label_42.setText(_translate("MainWindow", "Roll"))
        self.label_41.setText(_translate("MainWindow", "Yaw"))
        self.button_delta_orientation.setText(_translate("MainWindow", "DELTA\n"
"Orientation"))
        self.button_goto_orientation.setText(_translate("MainWindow", "GOTO\n"
"Orientation"))
        self.label_43.setText(_translate("MainWindow", "Pitch"))
        self.buttron_delta_pose.setText(_translate("MainWindow", "DELTA Pose"))
        self.button_goto_pose.setText(_translate("MainWindow", "GOTO Pose"))
        self.radioButton_10.setText(_translate("MainWindow", "Millimeters"))
        self.radioButton_11.setText(_translate("MainWindow", "Meters"))
        self.radioButton_12.setText(_translate("MainWindow", "Degrees"))
        self.radioButton_13.setText(_translate("MainWindow", "Radians"))
        self.end_effector_pose.setTitle(_translate("MainWindow", "End Effector Pose"))
        self.label_52.setText(_translate("MainWindow", "Roll:"))
        self.label_53.setText(_translate("MainWindow", "Z:"))
        self.label_54.setText(_translate("MainWindow", "Yaw:"))
        self.label_55.setText(_translate("MainWindow", "X:"))
        self.label_56.setText(_translate("MainWindow", "Y:"))
        self.label_57.setText(_translate("MainWindow", "Pitch:"))
        self.x.setText(_translate("MainWindow", "0.000000"))
        self.y.setText(_translate("MainWindow", "0.000000"))
        self.z.setText(_translate("MainWindow", "0.000000"))
        self.r.setText(_translate("MainWindow", "0.000000"))
        self.p.setText(_translate("MainWindow", "0.000000"))
        self.y_.setText(_translate("MainWindow", "0.000000"))
        self.joint_revolution.setTitle(_translate("MainWindow", "Joint Revolution"))
        self.label_44.setText(_translate("MainWindow", "Joint 1"))
        self.label_45.setText(_translate("MainWindow", "Angle Mode"))
        self.label_47.setText(_translate("MainWindow", "Joint 2"))
        self.label_48.setText(_translate("MainWindow", "Joint 3"))
        self.label_49.setText(_translate("MainWindow", "Joint 4"))
        self.label_50.setText(_translate("MainWindow", "Joint 5"))
        self.label_51.setText(_translate("MainWindow", "Joint 6"))
        self.pushButton_88.setText(_translate("MainWindow", "DELTA Angle"))
        self.pushButton_87.setText(_translate("MainWindow", "GOTO Angle"))
        self.button_reset_angle.setText(_translate("MainWindow", "Reset"))
        self.radioButton_34.setText(_translate("MainWindow", "Degrees"))
        self.radioButton_35.setText(_translate("MainWindow", "Radians"))
        self.label_46.setText(_translate("MainWindow", "ABB IRB-120 Connected!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manipulation_arm_1), _translate("MainWindow", "Manual Control - Arm 1"))
        self.numerical_controls_2.setTitle(_translate("MainWindow", "Numerical Control - Pose"))
        self.label_70.setText(_translate("MainWindow", "Z"))
        self.label_85.setText(_translate("MainWindow", "X"))
        self.label_86.setText(_translate("MainWindow", "Y"))
        self.button_goto_position_2.setText(_translate("MainWindow", "GOTO\n"
"Position"))
        self.button_delta_position_2.setText(_translate("MainWindow", "DELTA\n"
"Position"))
        self.label_87.setText(_translate("MainWindow", "Roll"))
        self.label_88.setText(_translate("MainWindow", "Yaw"))
        self.button_delta_orientation_2.setText(_translate("MainWindow", "DELTA\n"
"Orientation"))
        self.button_goto_orientation_2.setText(_translate("MainWindow", "GOTO\n"
"Orientation"))
        self.label_89.setText(_translate("MainWindow", "Pitch"))
        self.buttron_delta_pose_2.setText(_translate("MainWindow", "DELTA Pose"))
        self.button_goto_pose_2.setText(_translate("MainWindow", "GOTO Pose"))
        self.radioButton_14.setText(_translate("MainWindow", "Millimeters"))
        self.radioButton_15.setText(_translate("MainWindow", "Meters"))
        self.radioButton_25.setText(_translate("MainWindow", "Degrees"))
        self.radioButton_26.setText(_translate("MainWindow", "Radians"))
        self.end_effector_pose_2.setTitle(_translate("MainWindow", "End Effector Pose"))
        self.label_90.setText(_translate("MainWindow", "Roll"))
        self.label_91.setText(_translate("MainWindow", "Z"))
        self.label_92.setText(_translate("MainWindow", "Yaw"))
        self.label_93.setText(_translate("MainWindow", "X"))
        self.label_94.setText(_translate("MainWindow", "Y"))
        self.label_95.setText(_translate("MainWindow", "Pitch"))
        self.label_96.setText(_translate("MainWindow", "NUROMEKA Indy7 Connected!"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Linear Jogging"))
        self.label_97.setText(_translate("MainWindow", "X"))
        self.label_98.setText(_translate("MainWindow", "Y"))
        self.label_99.setText(_translate("MainWindow", "Z"))
        self.label_100.setText(_translate("MainWindow", "Fine Step"))
        self.label_101.setText(_translate("MainWindow", "Normal Step"))
        self.label_102.setText(_translate("MainWindow", "Large Step"))
        self.label_103.setText(_translate("MainWindow", "Units"))
        self.radioButton_27.setText(_translate("MainWindow", "Meters"))
        self.radioButton_28.setText(_translate("MainWindow", "Centimeters"))
        self.radioButton_29.setText(_translate("MainWindow", "Millimiters"))
        self.button_x_plus_large_2.setText(_translate("MainWindow", "+\n"
"+\n"
"+"))
        self.button_x_minus_fine_2.setText(_translate("MainWindow", "x\n"
"-"))
        self.button_y_plus_large_2.setText(_translate("MainWindow", "+++"))
        self.button_y_minus_normal_2.setText(_translate("MainWindow", "y\n"
"--"))
        self.button_z_plus_normal_2.setText(_translate("MainWindow", "z\n"
"++"))
        self.button_x_plus_normal_2.setText(_translate("MainWindow", "x\n"
"++"))
        self.button_z_minus_normal_2.setText(_translate("MainWindow", "z\n"
"--"))
        self.button_z_minus_large_2.setText(_translate("MainWindow", "---"))
        self.button_y_plus_normal_2.setText(_translate("MainWindow", "y\n"
"++"))
        self.button_y_minus_fine_2.setText(_translate("MainWindow", "y\n"
"-"))
        self.button_z_plus_large_2.setText(_translate("MainWindow", "+++"))
        self.button_y_minus_large_2.setText(_translate("MainWindow", "---"))
        self.button_z_minus_fine_2.setText(_translate("MainWindow", "z\n"
"-"))
        self.button_x_minus_large_2.setText(_translate("MainWindow", "-\n"
"-\n"
"-"))
        self.button_y_plus_fine_2.setText(_translate("MainWindow", "y\n"
"+"))
        self.button_x_plus_fine_2.setText(_translate("MainWindow", "x\n"
"+"))
        self.button_x_minus_normal_2.setText(_translate("MainWindow", "x\n"
"--"))
        self.button_z_plus_fine_2.setText(_translate("MainWindow", "z\n"
"+"))
        self.joint_revolution_2.setTitle(_translate("MainWindow", "Joint Revolution"))
        self.label_104.setText(_translate("MainWindow", "Joint 1"))
        self.label_105.setText(_translate("MainWindow", "Angle Mode"))
        self.label_106.setText(_translate("MainWindow", "Joint 2"))
        self.label_107.setText(_translate("MainWindow", "Joint 3"))
        self.label_108.setText(_translate("MainWindow", "Joint 4"))
        self.label_109.setText(_translate("MainWindow", "Joint 5"))
        self.label_110.setText(_translate("MainWindow", "Joint 6"))
        self.pushButton_89.setText(_translate("MainWindow", "DELTA Angle"))
        self.pushButton_117.setText(_translate("MainWindow", "GOTO Angle"))
        self.button_reset_angle_2.setText(_translate("MainWindow", "Reset"))
        self.radioButton_36.setText(_translate("MainWindow", "Degrees"))
        self.radioButton_37.setText(_translate("MainWindow", "Radians"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manipulation_arm_2), _translate("MainWindow", "Manual Control - Arm 2"))
        self.define_task.setTitle(_translate("MainWindow", "Define Task"))
        self.task_type.setTitle(_translate("MainWindow", "Task Type"))
        self.radioButton.setText(_translate("MainWindow", "Linear Move"))
        self.radioButton_2.setText(_translate("MainWindow", "Open Gripper"))
        self.radioButton_3.setText(_translate("MainWindow", "Close Gripper"))
        self.radioButton_30.setText(_translate("MainWindow", "Approach>Linear"))
        self.radioButton_31.setText(_translate("MainWindow", "Uniform Move"))
        self.label_gripper_grip_2.setText(_translate("MainWindow", "Gripper Grip:"))
        self.label_gripper_open_2.setText(_translate("MainWindow", "Gripper Open:"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_6.setText(_translate("MainWindow", "Move Up"))
        self.pushButton_7.setText(_translate("MainWindow", "Move Down"))
        self.pushButton_10.setText(_translate("MainWindow", "Edit"))
        self.label_4.setText(_translate("MainWindow", "0 / 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Task Macro Record"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionRobot_Preference.setText(_translate("MainWindow", "Robot Preference"))
        self.actionController_Preference.setText(_translate("MainWindow", "Controller Preference"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_Configuration.setText(_translate("MainWindow", "Load Configuration"))
        self.actionSave_Configuration_as_File.setText(_translate("MainWindow", "Save Configuration as File"))

